- hosts: terraform-ansible
  become: yes
  tasks:
  - name: Instalando o python3, virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
  - name: Instalando dependÃªncias com pip
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework
  - name: verificando se o projeto ja foi iniciado
    stat:
      path: /home/ubuntu/tcc/setup/settings.py
    register: projeto
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
    when: not projeto.stat.exists
  - name: Alterando os hosts do settings 
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes


